require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe CodeExamplesController do

  # This should return the minimal set of attributes required to create a valid
  # CodeExample. As you add validations to CodeExample, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all code_examples as @code_examples" do
      code_example = CodeExample.create! valid_attributes
      get :index
      assigns(:code_examples).should eq([code_example])
    end
  end

  describe "GET show" do
    it "assigns the requested code_example as @code_example" do
      code_example = CodeExample.create! valid_attributes
      get :show, :id => code_example.id.to_s
      assigns(:code_example).should eq(code_example)
    end
  end

  describe "GET new" do
    it "assigns a new code_example as @code_example" do
      get :new
      assigns(:code_example).should be_a_new(CodeExample)
    end
  end

  describe "GET edit" do
    it "assigns the requested code_example as @code_example" do
      code_example = CodeExample.create! valid_attributes
      get :edit, :id => code_example.id.to_s
      assigns(:code_example).should eq(code_example)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new CodeExample" do
        expect {
          post :create, :code_example => valid_attributes
        }.to change(CodeExample, :count).by(1)
      end

      it "assigns a newly created code_example as @code_example" do
        post :create, :code_example => valid_attributes
        assigns(:code_example).should be_a(CodeExample)
        assigns(:code_example).should be_persisted
      end

      it "redirects to the created code_example" do
        post :create, :code_example => valid_attributes
        response.should redirect_to(CodeExample.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved code_example as @code_example" do
        # Trigger the behavior that occurs when invalid params are submitted
        CodeExample.any_instance.stub(:save).and_return(false)
        post :create, :code_example => {}
        assigns(:code_example).should be_a_new(CodeExample)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        CodeExample.any_instance.stub(:save).and_return(false)
        post :create, :code_example => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested code_example" do
        code_example = CodeExample.create! valid_attributes
        # Assuming there are no other code_examples in the database, this
        # specifies that the CodeExample created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        CodeExample.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => code_example.id, :code_example => {'these' => 'params'}
      end

      it "assigns the requested code_example as @code_example" do
        code_example = CodeExample.create! valid_attributes
        put :update, :id => code_example.id, :code_example => valid_attributes
        assigns(:code_example).should eq(code_example)
      end

      it "redirects to the code_example" do
        code_example = CodeExample.create! valid_attributes
        put :update, :id => code_example.id, :code_example => valid_attributes
        response.should redirect_to(code_example)
      end
    end

    describe "with invalid params" do
      it "assigns the code_example as @code_example" do
        code_example = CodeExample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CodeExample.any_instance.stub(:save).and_return(false)
        put :update, :id => code_example.id.to_s, :code_example => {}
        assigns(:code_example).should eq(code_example)
      end

      it "re-renders the 'edit' template" do
        code_example = CodeExample.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        CodeExample.any_instance.stub(:save).and_return(false)
        put :update, :id => code_example.id.to_s, :code_example => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested code_example" do
      code_example = CodeExample.create! valid_attributes
      expect {
        delete :destroy, :id => code_example.id.to_s
      }.to change(CodeExample, :count).by(-1)
    end

    it "redirects to the code_examples list" do
      code_example = CodeExample.create! valid_attributes
      delete :destroy, :id => code_example.id.to_s
      response.should redirect_to(code_examples_url)
    end
  end

end
